# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 15s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'poktpool-monitoring'

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']
  
  - job_name: 'blackbox'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - blackbox:9115   # For Windows and macOS replace with - host.docker.internal:9115

  - job_name: 'blackbox_poktpool_website_check'
    metrics_path: /probe
    params:
      module: [poktpool_website_check]  # Look for POKTpool website content
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - https://poktpool.com    # Main website
        - https://www.poktpool.com # www subdomain
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox:9115"  # Blackbox exporter.
      - target_label: region
        replacement: "production"

  - job_name: 'blackbox_poktpool_api_check'
    metrics_path: /probe
    params:
      module: [poktpool_api_check]  # Look for POKTpool API endpoints
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
        - https://poktpool.com/api/health    # API health endpoint (if exists)
        - https://poktpool.com/status        # Status endpoint (if exists)
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox:9115"

  - job_name: 'blackbox_poktpool_ssl_check'
    metrics_path: /probe
    params:
      module: [https_connect]  # Check SSL/TLS connectivity
    static_configs:
      - targets:
        - https://poktpool.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox:9115"
