
x-loki:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    max-size: 5m
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: '3'
    max-file: '3'
    keep-file: 'false'

services:
  traefik:
    cpus: 2
    mem_limit: 2G
    image: traefik:latest
    container_name: traefik
    restart: always
    env_file: 
      - .env
    ports:
      - 80:80
      - 443:443 
      - 8082 # metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./loadbalancer/traefik.yml:/traefik.yml:ro
      - ./loadbalancer/services/:/etc/traefik/services/:ro
      - ./loadbalancer/certs:/letsencrypt
    logging: *loki-logging

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/data:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    restart: always
    logging: *loki-logging

  grafana:
    image: grafana/grafana:latest
    container_name: grafana 
    user: root
    ports:
    -  "3000:3000"
    volumes:
      - ./monitoring/grafana/data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file: 
      - .env
    restart: always
    logging: *loki-logging

  loki:
    image: grafana/loki:3.4.4
    container_name: loki
    volumes:
      - ./monitoring/loki/config.yaml:/etc/loki/local-config.yaml
      - ./monitoring/loki/data:/data/loki
    expose:
      - 3100
    ports:
      - "3100:3100" 
    command: --config.file=/etc/loki/local-config.yaml
    restart: always
    logging: *loki-logging

  blackbox:
    container_name: blackbox
    image: prom/blackbox-exporter:latest
    privileged: true
    expose:
      - '9115'  
    volumes:
      - ./monitoring/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter 
    expose:
      - 9100 
    restart: always
    logging: *loki-logging
