http:
  routers:
    poktpool-monitoring-local:
      rule: Host(`monitoring.localhost`)
      service: poktpool-monitoring 
      priority: 1
      entryPoints:
      - web
  services:
    poktpool-monitoring-local:
      loadBalancer:
        passHostHeader:  true
        servers:
          - url: http://grafana:3000
