http:
  routers:
    poktpool-monitoring:
      rule: Host(`monitoring.{{ env "DOMAIN" }}`) 
      service: poktpool-monitoring 
      priority: 1
      entryPoints:
      - web
      - websecure 
      middlewares:
      - https-redirect
      tls:
        certResolver: https-resolver
  services:
    poktpool-monitoring:
      loadBalancer:
        passHostHeader: true 
        servers:
          - url: http://grafana:3000/
