apiVersion: 1
contactPoints:
    - orgId: 1
      name: Discord Alerts
      receivers:
        - uid: discord-alerts-receiver
          type: discord
          settings:
            avatar_url: https://cdn.discordapp.com/attachments/123456789/123456789/alert-bot.png
            message: |-
                {{ define "alerts.message" -}}
                  {{ if .Alerts.Firing -}}
                    🔴 **{{ len .Alerts.Firing }} Firing Alert(s)**
                    {{ template "alerts.summarize" .Alerts.Firing }}
                  {{- end }}
                  {{- if .Alerts.Resolved -}}
                    ✅ **{{ len .Alerts.Resolved }} Resolved Alert(s)**
                    {{ template "alerts.summarize" .Alerts.Resolved }}
                  {{- end }}
                {{- end }}

                {{ define "alerts.summarize" -}}
                  {{ range . -}}
                  **{{ index .Labels "alertname" }}**
                  • **Instance:** {{ index .Labels "instance" }}
                  • **Severity:** {{ index .Labels "severity" }}
                  • **Summary:** {{ index .Annotations "summary" }}
                  {{ if index .Annotations "description" }}
                  • **Description:** {{ index .Annotations "description" }}
                  {{ end }}
                  {{ if index .Annotations "value" }}
                  • **Value:** {{ index .Annotations "value" }}
                  {{ end }}
                  
                  {{ end }}
                {{ end }}
            title: '🚨 POKTpool Monitoring Alert'
            url: ${DISCORD_WEBHOOK_URL}
            use_discord_username: false
          disableResolveMessage: false
